name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Sphinx Build
    - uses: ammaraskar/sphinx-action@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        args: "docs/ docs2/"

